# Generated by Django 5.0.2 on 2024-02-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('stock', models.IntegerField()),
                ('presentacion', models.CharField(choices=[('1', 'Caja'), ('2', 'Pieza'), ('3', 'Paquete')], max_length=1, verbose_name='Presentación')),
                ('color', models.CharField(choices=[('r', 'Rojo'), ('a', 'Azul'), ('v', 'Verde')], max_length=1)),
            ],
        ),
    ]
