version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: curso_mita
    #restart: always
    depends_on:
      - db-videojuegos
    ports:
      - 8000:8000
      # - 80:80
    volumes:
      - ./app/:/app

  db-videojuegos:
    image: mariadb
    container_name: videojuegos-db
    #restart: always
    environment:
      MYSQL_DATABASE: videojuegos
      MYSQL_USER: videojuegos_user
      MYSQL_PASSWORD: admin12345
      MYSQL_ROOT_PASSWORD: admin12345
    volumes:
      - db-videojuegos:/var/lib/mysql
    ports:
      - 3310:3306

  db-comisiones:
    image: mariadb
    container_name: comisiones-db
    #restart: always
    environment:
      MYSQL_DATABASE: comisiones
      MYSQL_USER: comisiones_user
      MYSQL_PASSWORD: admin12345
      MYSQL_ROOT_PASSWORD: admin12345
    volumes:
      - db-comisiones:/var/lib/mysql
    ports:
      - 3320:3306

volumes:
  db-videojuegos:
  db-comisiones:
