# Generated by Django 5.0.2 on 2024-06-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_compras', '0002_alter_articulo_rin_alter_detalle_compra_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
    ]
